# Generated by Django 5.0.7 on 2024-10-04 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IDCardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='api.idcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ID Card Data',
                'verbose_name_plural': 'ID Card Data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=2.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
