# Generated by Django 5.0.7 on 2024-10-06 11:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_idcard_expiry_date_idcarddata_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcarddata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='wallet',
            table='wallet',
        ),
        migrations.CreateModel(
            name='ApiWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=2.0, max_digits=10)),
                ('card_number', models.CharField(max_length=100, null=True)),
                ('deduction_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_wallet_log',
            },
        ),
    ]
