# Generated by Django 5.0.7 on 2024-10-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_idcarddata_user_alter_wallet_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='card_number',
            field=models.CharField(max_length=100),
        ),
    ]
