# Generated by Django 3.2.25 on 2024-10-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_idcard_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='apiwallet',
            name='card_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='apiwallet',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='apiwallet',
            name='deduction_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
